/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as ApplyIndexRouteImport } from './routes/apply.index'
import { Route as PortalTrackingRouteImport } from './routes/portal.tracking'
import { Route as PortalRestrictedRouteImport } from './routes/portal.restricted'
import { Route as PortalResourcesRouteImport } from './routes/portal.resources'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalInboxRouteImport } from './routes/portal.inbox'
import { Route as PortalEventsRouteImport } from './routes/portal.events'
import { Route as PortalDashboardRouteImport } from './routes/portal.dashboard'
import { Route as PortalCertificatesRouteImport } from './routes/portal.certificates'
import { Route as ApplyDashboardRouteImport } from './routes/apply.dashboard'
import { Route as ApplyAccountRouteImport } from './routes/apply.account'
import { Route as EventsEventIdRegisterRouteImport } from './routes/events.$eventId.register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyIndexRoute = ApplyIndexRouteImport.update({
  id: '/apply/',
  path: '/apply/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTrackingRoute = PortalTrackingRouteImport.update({
  id: '/portal/tracking',
  path: '/portal/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRestrictedRoute = PortalRestrictedRouteImport.update({
  id: '/portal/restricted',
  path: '/portal/restricted',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalResourcesRoute = PortalResourcesRouteImport.update({
  id: '/portal/resources',
  path: '/portal/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/portal/profile',
  path: '/portal/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalInboxRoute = PortalInboxRouteImport.update({
  id: '/portal/inbox',
  path: '/portal/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalEventsRoute = PortalEventsRouteImport.update({
  id: '/portal/events',
  path: '/portal/events',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/portal/dashboard',
  path: '/portal/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalCertificatesRoute = PortalCertificatesRouteImport.update({
  id: '/portal/certificates',
  path: '/portal/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyDashboardRoute = ApplyDashboardRouteImport.update({
  id: '/apply/dashboard',
  path: '/apply/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyAccountRoute = ApplyAccountRouteImport.update({
  id: '/apply/account',
  path: '/apply/account',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRegisterRoute = EventsEventIdRegisterRouteImport.update({
  id: '/events/$eventId/register',
  path: '/events/$eventId/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply/account': typeof ApplyAccountRoute
  '/apply/dashboard': typeof ApplyDashboardRoute
  '/portal/certificates': typeof PortalCertificatesRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/events': typeof PortalEventsRoute
  '/portal/inbox': typeof PortalInboxRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/resources': typeof PortalResourcesRoute
  '/portal/restricted': typeof PortalRestrictedRoute
  '/portal/tracking': typeof PortalTrackingRoute
  '/apply/': typeof ApplyIndexRoute
  '/events/': typeof EventsIndexRoute
  '/events/$eventId/register': typeof EventsEventIdRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply/account': typeof ApplyAccountRoute
  '/apply/dashboard': typeof ApplyDashboardRoute
  '/portal/certificates': typeof PortalCertificatesRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/events': typeof PortalEventsRoute
  '/portal/inbox': typeof PortalInboxRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/resources': typeof PortalResourcesRoute
  '/portal/restricted': typeof PortalRestrictedRoute
  '/portal/tracking': typeof PortalTrackingRoute
  '/apply': typeof ApplyIndexRoute
  '/events': typeof EventsIndexRoute
  '/events/$eventId/register': typeof EventsEventIdRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply/account': typeof ApplyAccountRoute
  '/apply/dashboard': typeof ApplyDashboardRoute
  '/portal/certificates': typeof PortalCertificatesRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/events': typeof PortalEventsRoute
  '/portal/inbox': typeof PortalInboxRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/resources': typeof PortalResourcesRoute
  '/portal/restricted': typeof PortalRestrictedRoute
  '/portal/tracking': typeof PortalTrackingRoute
  '/apply/': typeof ApplyIndexRoute
  '/events/': typeof EventsIndexRoute
  '/events/$eventId/register': typeof EventsEventIdRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply/account'
    | '/apply/dashboard'
    | '/portal/certificates'
    | '/portal/dashboard'
    | '/portal/events'
    | '/portal/inbox'
    | '/portal/login'
    | '/portal/profile'
    | '/portal/resources'
    | '/portal/restricted'
    | '/portal/tracking'
    | '/apply/'
    | '/events/'
    | '/events/$eventId/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply/account'
    | '/apply/dashboard'
    | '/portal/certificates'
    | '/portal/dashboard'
    | '/portal/events'
    | '/portal/inbox'
    | '/portal/login'
    | '/portal/profile'
    | '/portal/resources'
    | '/portal/restricted'
    | '/portal/tracking'
    | '/apply'
    | '/events'
    | '/events/$eventId/register'
  id:
    | '__root__'
    | '/'
    | '/apply/account'
    | '/apply/dashboard'
    | '/portal/certificates'
    | '/portal/dashboard'
    | '/portal/events'
    | '/portal/inbox'
    | '/portal/login'
    | '/portal/profile'
    | '/portal/resources'
    | '/portal/restricted'
    | '/portal/tracking'
    | '/apply/'
    | '/events/'
    | '/events/$eventId/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyAccountRoute: typeof ApplyAccountRoute
  ApplyDashboardRoute: typeof ApplyDashboardRoute
  PortalCertificatesRoute: typeof PortalCertificatesRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalEventsRoute: typeof PortalEventsRoute
  PortalInboxRoute: typeof PortalInboxRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalResourcesRoute: typeof PortalResourcesRoute
  PortalRestrictedRoute: typeof PortalRestrictedRoute
  PortalTrackingRoute: typeof PortalTrackingRoute
  ApplyIndexRoute: typeof ApplyIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  EventsEventIdRegisterRoute: typeof EventsEventIdRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/': {
      id: '/apply/'
      path: '/apply'
      fullPath: '/apply/'
      preLoaderRoute: typeof ApplyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/tracking': {
      id: '/portal/tracking'
      path: '/portal/tracking'
      fullPath: '/portal/tracking'
      preLoaderRoute: typeof PortalTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/restricted': {
      id: '/portal/restricted'
      path: '/portal/restricted'
      fullPath: '/portal/restricted'
      preLoaderRoute: typeof PortalRestrictedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/resources': {
      id: '/portal/resources'
      path: '/portal/resources'
      fullPath: '/portal/resources'
      preLoaderRoute: typeof PortalResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/portal/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/inbox': {
      id: '/portal/inbox'
      path: '/portal/inbox'
      fullPath: '/portal/inbox'
      preLoaderRoute: typeof PortalInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/events': {
      id: '/portal/events'
      path: '/portal/events'
      fullPath: '/portal/events'
      preLoaderRoute: typeof PortalEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/portal/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/certificates': {
      id: '/portal/certificates'
      path: '/portal/certificates'
      fullPath: '/portal/certificates'
      preLoaderRoute: typeof PortalCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/dashboard': {
      id: '/apply/dashboard'
      path: '/apply/dashboard'
      fullPath: '/apply/dashboard'
      preLoaderRoute: typeof ApplyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/account': {
      id: '/apply/account'
      path: '/apply/account'
      fullPath: '/apply/account'
      preLoaderRoute: typeof ApplyAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/register': {
      id: '/events/$eventId/register'
      path: '/events/$eventId/register'
      fullPath: '/events/$eventId/register'
      preLoaderRoute: typeof EventsEventIdRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyAccountRoute: ApplyAccountRoute,
  ApplyDashboardRoute: ApplyDashboardRoute,
  PortalCertificatesRoute: PortalCertificatesRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalEventsRoute: PortalEventsRoute,
  PortalInboxRoute: PortalInboxRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalResourcesRoute: PortalResourcesRoute,
  PortalRestrictedRoute: PortalRestrictedRoute,
  PortalTrackingRoute: PortalTrackingRoute,
  ApplyIndexRoute: ApplyIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  EventsEventIdRegisterRoute: EventsEventIdRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
