name: Deploy Frontend

on:
  push:
    branches: [main, develop, release]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: microsoft-student-community-qcu/qcu-msc-cicd/.github/workflows/deploy-frontend.yml@main
    secrets:
      azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
      azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      cloudflare-zone-id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      vite-sentry-dsn: ${{ secrets.VITE_SENTRY_DSN }}

